### PR TITLE
Adds ADO Pipeline

### PR DESCRIPTION
**Pull request by marlenabowen**
Initial pipeline setup

### CODE REVIEW

**Review by Ugochez — CHANGES_REQUESTED** [review]
Hello Marlena , These are some requested changes to the azure-pipelines.yml. Please let me know if you have any questions.
 
1. I would create the build job in this order:
    task - restore Dependencies
    task - Build Application
    task - Test Application - use the .NETCore task to run unit tests.
    task - PublishArtifacts
2. I think the Archive Task and the Publish Task might be doing the same thing. 
3. We need to deploy artifacts to Dev and/or QA perform additional tests and get the necessary approvals before deploying to production. create new stages:
      stage - Deploy to Dev
      stage - Deploy to QA - with necessary approval steps in the process
4. Credentials should never be included in our file. We can use the Azure KeyVault passing in a secret.
5. Please remove the values on lines 97 and 98 and instead we can add:
    task - AzureKeyVault - will include service connection, name of keyvault etc.
6. Indentation. We can use an additional SonarCloud task which checks for code quality, duplication and code scans. Code/Yaml lint or validator can also be another quick option to make sure this yaml file is well indented.  

Thanks you. Ugo

**Comment by Ugochez** [comment]
See suggested changes above.

**Comment by marlenabowen** [comment]
Hey @Ugochez, you should have received an email invitation to become a collaborator on this repo so that you can do a line-by-line peer review here. Please let me know if you didn't receive it and I'll re-send.

Can you help me understand why you think the archive and publish tasks do the same thing?

**Comment by Ugochez** [comment]
Hi @marlenabowen , The Archive task archives the repo while the publish task publishes the Artifacts. Thanks for clarifying I should have asked the question. I will go ahead and accept the invitation now

**Pull request merged**
